version: "3.8"

services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "${FILEBROWSER_BIND_ADDRESS:-127.0.0.1}:44443:8080"
    volumes:
      - ./filebrowser_config:/config
      - ./aria2-downloads:/data
      - /root/ssl:/ssl:ro
    environment:
      - FB_BASEURL=/filebrowser
    restart: always

  Aria2-Pro:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=true
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Shanghai
      - RPC_SECRET=${RPC_SECRET:?RPC_SECRET must be set}
      - RPC_SECURE=true
      - RPC_CERTIFICATE=/ssl/us-45.xxx.xxx/us-45.xxx.xxx.cer
      - RPC_PRIVATE_KEY=/ssl/us-45.xxx.xxx/us-45.xxx.xxx.key
    volumes:
      - ./aria2-config:/config
      - ./aria2-downloads:/downloads
      - /root/ssl:/ssl:ro
    ports:
      - "${ARIA2_BIND_ADDRESS:-127.0.0.1}:6800:6800"
      - "${ARIA2_BIND_ADDRESS:-127.0.0.1}:6888:6888"
      - "${ARIA2_BIND_ADDRESS:-127.0.0.1}:6888:6888/udp"
    restart: unless-stopped
# Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m

# AriaNg is just a static web page, usually you only need to deploy on a single host.
  AriaNg:
    container_name: ariang
    image: p3terx/ariang
    command: --port 6880 --ipv6
    ports:
      - "127.0.0.1:6880:6880"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
