" __  ____   __  _   ___     _____ __  __ ____   ____
"|  \/  \ \ / / | \ | \ \   / /_ _|  \/  |  _ \ / ___|
"| |\/| |\ V /  |  \| |\ \ / / | || |\/| | |_) | |
"| |  | | | |   | |\  | \ V /  | || |  | |  _ <| |___
"|_|  |_| |_|   |_| \_|  \_/  |___|_|  |_|_| \_\\____|
"
"
" author: h12345jack
"
" ============== plug config 
call plug#begin()

" Plugin: NerdTree
Plug 'preservim/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'

" Plugin: Editing
Plug 'tpope/vim-surround' " example: cs'}
Plug 'tpope/vim-commentary' " 

" Plugin: UI
Plug 'liuchengxu/space-vim-dark'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" Plugin: Encoding
Plug 'mbbill/fencview', {'on': 'FencAutoDetect'}

" Plugin: complete
Plug 'honza/vim-snippets'

" Plugin: markdown
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
Plug 'ferrine/md-img-paste.vim'

Plug 'mbbill/undotree'
Plug 'airblade/vim-gitgutter'


call plug#end()


" ======== General setting 

set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936
set termencoding=utf-8
set encoding=utf-8
filetype plugin indent on "Enabling Plugin & Indent
syntax on "Turning Syntax on
set wildmenu " Enable enhanced tab autocomplete.
set wildmode=list:longest,full " Complete till longest string, then open the wildmenu.
set ruler
set mouse=a
set laststatus=2
set nobackup
set noswapfile
" copy from requests author
set number
set nocompatible  " cancle the campatitble mode
set backspace=2   " backspace for delete bug
" set textwidth=79  " lines longer than 79 columns will be broken
set softtabstop=4 " insert/delete 4 spaces when hitting a TAB/BACKSPACE
set shiftround    " round indent to multiple of 'shiftwidth'

set tabstop=4  "tab space 
set shiftwidth=4  " operation >> indents 4 columns; << unindents 4 columns
set expandtab     " insert spaces when hitting TABs
set cindent "C language autoindent
set smarttab
set linebreak
set splitbelow "https://vi.stackexchange.com/questions/16795/how-could-i-create-a-terminal-at-the-bottom
" set termwinsize=20*0

set list
set listchars=tab:>-,trail:-

set history=1024
set clipboard=unnamed " import config to w/r memory register

set pastetoggle=<F2>
" reopen to last position
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal! g`\"" | endif
endif

"================ space-vim-dark config 
colorscheme space-vim-dark

" ================ nerdtree config 
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'
" show hidden files: https://stackoverflow.com/questions/5057359/how-can-i-show-hidden-files-starting-with-period-in-nerdtree

let NERDTreeShowHidden=1
let g:NERDTreeWinSize = 25
" let g:NERDTreeQuitOnOpen = 1
" keymap

" open a NERDTree automatically when vim starts up if no files were specified
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" open NERDTree automatically when vim starts up on opening a directory
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | exe 'cd '.argv()[0] | endif

" close vim if the only window left open is a NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" map 
let g:NERDTreeGitStatusIndicatorMapCustom = {
    \ "Modified"  : "✹",
    \ "Staged"    : "✚",
    \ "Untracked" : "✭",
    \ "Renamed"   : "➜",
    \ "Unmerged"  : "═",
    \ "Deleted"   : "✖",
    \ "Dirty"     : "✗",
    \ "Clean"     : "✔︎",
    \ 'Ignored'   : '☒',
    \ "Unknown"   : "?"
    \ }


" ======== md-image-paste
autocmd FileType markdown nmap <buffer><silent> <leader>p :call mdip#MarkdownClipboardImage()<CR>
let g:mdip_imgdir = 'assets'


" ================ my configs
" map jk to esc 
let mapleader="\<space>"
let g:mapleader="\<space>"
imap jk <Esc> 
imap kj <Esc>

" near to SPC f e d in spacemacs
nmap <leader>fed :vi ~/.vimrc<cr>

" Split window
nmap <leader>ws :split<Return><C-w>w
nmap <leader>wv :vsplit<Return><C-w>w

" Move window
map <leader>wh <C-w>h
map <leader>wk <C-w>k
map <leader>wj <C-w>j
map <leader>wl <C-w>l
map <leader>wq <C-w>q
map <leader>pt :NERDTreeToggle<CR>



